{
 "title": "Playwright Prometheus Remote Write Reporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "probe_id", "label": "ID", "query": { "query": "label_values(pw_test, id)" } },
   {
    "name": "steps",
    "query": {
     "query": "query_result(sort_desc(count_over_time(pw_step_status{testId=\"${probe_id}\"}[24h])))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pw_test{id=\"${probe_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pw_test{id=\"${probe_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pw_test{id=\"${probe_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pw_test{id=\"${probe_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Steps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pw_test{id=\"${probe_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Retries" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pw_test{id=\"${probe_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pw_test_duration{id=\"${probe_id}\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  { "title": "Steps Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "${steps:text}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "repeat": "steps",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pw_step_status{testId=\"${probe_id}\", stepId=\"${steps:value}\"}",
     "legendFormat": "{{stepTitle}}"
    }
   ]
  },
  { "title": "Steps Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "${steps:text}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "repeat": "steps",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pw_step_duration{testId=\"${probe_id}\", stepId=\"${steps:value}\"}",
     "legendFormat": "{{stepTitle}}"
    }
   ]
  },
  { "title": "Steps Failed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max by (stepId, stepTitle, errorMessage, location, testId, testTitle) (\n  pw_step_status{testId=\"${probe_id}\", errorMessage!=\"\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}