name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  node-pnpm:
    name: Node.js+pnpm - setup, build and test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Generate build
        run: pnpm build
      - uses: changesets/action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
          commit: "[ci] release"
          title: "[ci] release"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
